export const  DATOS = [
    {
      id: '1',
      nombre: 'Mario Alfredo',
      materia: 'Administración de Redes',
      universidad: 'UTN',
      carrera: 'ITI',
      pais: 'Costa Rica',
      modalidad: 'Virtual',
      horario: 'Martes y Jueves en la mañana',
      imagen: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
    {
      id: '2',
      nombre: 'Hermenegildo Paladino',
      materia: 'Cálculo y Álgebra Lineal',
      universidad: 'UTN',
      carrera: 'ITI',
      pais: 'Costa Rica',
      modalidad: 'Presencial',
      horario: 'Viernes en la mañana',
      imagen: 'https://randomuser.me/api/portraits/men/2.jpg',
    },
    {
      id: '3',
      nombre: 'Keven Antonio Solis',
      materia: 'Programación I',
      pais: 'Colombia',
      universidad: 'UTN',
      carrera: 'ITI',
      modalidad: 'Presencial',
      horario: 'Viernes en la tarde',
      imagen: 'https://randomuser.me/api/portraits/men/3.jpg',
    },
    {
      id: '4',
      nombre: 'Mario Alfredo',
      materia: 'Administración de Servidores',
      pais: 'Colombia',
      universidad: 'UPTC',
      carrera: 'ITI',
      modalidad: 'Presencial',
      horario: 'Martes y Jueves 9am - 10am',
      imagen: 'https://randomuser.me/api/portraits/men/4.jpg',
    },
    {
      id: '6',
      nombre: 'Messi Ronaldo Diaz',
      materia: 'Programación II',
      pais: 'Colombia',
      universidad: 'UPTC',
      carrera: 'ITI',
      modalidad: 'Presencial',
      horario: 'Viernes 11am - 12pm',
      imagen: 'https://randomuser.me/api/portraits/men/6.jpg',
    },
    {
      id: '7',
      nombre: 'Enrique Adonai',
      materia: 'Administración de Redes',
      pais: 'Colombia',
      universidad: 'UPTC',
      carrera: 'ITI',
      modalidad: 'Híbrida',
      horario: 'Lunes 5am - 1pm',
      imagen: 'https://randomuser.me/api/portraits/men/7.jpg',
    },
  ];